export const categories = ["bollywood", "hollywood", "south", "gujarati", "marvel_studio", "tv_shows", "web_series"]
export const genres = ['comedy','thriller','adventure','animation','drama','fantasy','horror','mystery','romantic','action','crime','science_fiction']
export const genresWithDescriptions = [
    { genre: 'comedy', description: 'Designed to entertain and amuse with lighthearted, humorous content.' },
    { genre: 'thriller', description: 'Intense and suspenseful, often involving high-stakes and unexpected twists.' },
    { genre: 'adventure', description: 'Focuses on exciting, action-filled journeys and explorations.' },
    { genre: 'animation', description: 'Utilizes animated visuals to tell imaginative stories across various genres.' },
    { genre: 'drama', description: 'Emphasizes emotional narratives, character development, and realistic situations.' },
    { genre: 'fantasy', description: 'Features magical, mythical, or supernatural elements set in imaginative worlds.' },
    { genre: 'horror', description: 'Aims to evoke fear and suspense, often involving supernatural or terrifying scenarios.' },
    { genre: 'mystery', description: 'Centers on solving puzzles or uncovering secrets, often with a detective or investigator.' },
    { genre: 'romantic', description: 'Focuses on love stories and emotional relationships between characters.' },
    { genre: 'action', description: 'Characterized by dynamic sequences, physical feats, and high-energy scenes.' },
    { genre: 'crime', description: 'Explores criminal activity, law enforcement, and moral dilemmas surrounding justice.' },
    { genre: 'science_fiction', description: 'Speculative content based on futuristic technology, space exploration, and scientific advancements.' }
];
export const movies = [
    {
        id: 1,
        title: 'The Shawshank Redemption',
        slug: 'the-shawshank-redemption',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        rating: 9.3,
        duration: 142,
        subtitleId: 2,
        year: 1994,
        size: '1.5 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=NmzuHjWmXOc',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 9,
        title: 'Mystery of the Sea',
        slug: 'mystery-of-the-sea',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/fB4YSa8R9kCnzbYaUyBc23BgsmZ.jpg',
        description: 'A deep-sea explorer uncovers an ancient secret that threatens the future of humanity.',
        rating: 8.1,
        duration: 134,
        subtitleId: 2,
        year: 2021,
        size: '1.8 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-mystery-sea',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 3,
        title: 'The Dark Knight',
        slug: 'the-dark-knight',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        description: 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
        rating: 9,
        duration: 152,
        subtitleId: 2,
        year: 2008,
        size: '2.5 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 1
    },
    {
        id: 11,
        title: 'Lost in the Wild',
        slug: 'lost-in-the-wild',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/xPZvpJBhAwMgc6A2JIffrPcTIdN.jpg',
        description: 'A survival expert must rely on her skills when she becomes stranded in a remote jungle.',
        rating: 7.6,
        duration: 128,
        subtitleId: 2,
        year: 2020,
        size: '1.4 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-lost-wild',
        status: 'Available',
        genreId: 4,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 10,
        title: 'Code Breaker',
        slug: 'code-breaker',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/rvsbOBVFDJl9VGef6BGW0MvCkFK.jpg',
        description: 'A hacker is drawn into a world of espionage after cracking an unbreakable code.',
        rating: 8.3,
        duration: 142,
        subtitleId: 2,
        year: 2023,
        size: '2.0 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-code-breaker',
        status: 'Available',
        genreId: 5,
        downloadlinkId: 2,
        categoryId: 1
    },
    {
        id: 6,
        title: 'Forrest Gump',
        slug: 'forrest-gump',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
        description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
        rating: 8.8,
        duration: 142,
        subtitleId: 2,
        year: 1994,
        size: '2.0 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=bLvqoHBptjg',
        status: 'Available',
        genreId: 10,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 8,
        title: 'The Forgotten Planet',
        slug: 'the-forgotten-planet',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/xSbMDb2Vx06zamaiw6iIAVRjcj6.jpg',
        description: 'A group of astronauts land on a mysterious planet where the laws of physics don’t apply.',
        rating: 7.8,
        duration: 120,
        subtitleId: 2,
        year: 2022,
        size: '1.5 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-forgotten-planet',
        status: 'Available',
        genreId: 9,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 4,
        title: 'Inception',
        slug: 'inception',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
        description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        rating: 8.8,
        duration: 148,
        subtitleId: 2,
        year: 2010,
        size: '2.3 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 5,
        title: 'Pulp Fiction',
        slug: 'pulp-fiction',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        rating: 8.9,
        duration: 154,
        subtitleId: 2,
        year: 1994,
        size: '2.0 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
        status: 'Available',
        genreId: 1,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 7,
        title: 'Fight Club',
        slug: 'fight-club',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
        description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.',
        rating: 8.8,
        duration: 139,
        subtitleId: 2,
        year: 1999,
        size: '1.8 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/watch?v=qtRKdVHc-cE',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 1
    },
    {
        id: 2,
        title: 'The Godfather',
        slug: 'the-godfather',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
        description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        rating: 9.2,
        duration: 175,
        subtitleId: 2,
        year: 1972,
        size: '2.0 GB',
        quality: '1080p',
        youtubelink: 'https://www.youtube.com/embed/UaVTIH8mujA',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 13,
        title: 'Parallel Universe',
        slug: 'parallel-universe',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/ailiI7b0eSDGgicQhAKGZHKYB16.jpg',
        description: 'A physicist discovers a way to travel between parallel worlds, but each jump has dangerous consequences.',
        rating: 8.7,
        duration: 145,
        subtitleId: 2,
        year: 2023,
        size: '2.1 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-parallel-universe',
        status: 'Available',
        genreId: 10,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 12,
        title: 'City of Shadows',
        slug: 'city-of-shadows',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/kB2Kys2Y4aizb1uMVqCwPOLMsVK.jpg',
        description: 'In a dystopian future, a detective uncovers a conspiracy that controls the fate of the world.',
        rating: 8.5,
        duration: 150,
        subtitleId: 2,
        year: 2024,
        size: '2.3 GB',
        quality: '4K',
        youtubelink: 'https://www.youtube.com/embed/hTMfUlcHi9U',
        status: 'Available',
        genreId: 13,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 16,
        title: 'The Last Guardian',
        slug: 'the-last-guardian',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/sGL5lHEWUDxFaPjYPVQGoNLojdn.jpg',
        description: 'An ancient warrior is awakened in modern times to fight a great evil that threatens the world.',
        rating: 7.5,
        duration: 147,
        subtitleId: 2,
        year: 2020,
        size: '1.6 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-last-guardian',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 14,
        title: 'Terminator Judgment Day',
        slug: 'terminator-judgment-day',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg',
        description: 'In a world where humans and AI live side by side, a new threat emerges that could destroy them both.',
        rating: 7.9,
        duration: 132,
        subtitleId: 2,
        year: 2022,
        size: '1.7 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-cybernetic-dawn',
        status: 'Available',
        genreId: 2,
        downloadlinkId: 2,
        categoryId: 1
    },
    {
        id: 15,
        title: 'Echoes of Time',
        slug: 'echoes-of-time',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/ytYcdIpYE73LjnyY3ufQ3ur2NHn.jpg',
        description: 'A time traveler gets trapped in a loop, living the same day over and over again, trying to change the future.',
        rating: 8.2,
        duration: 138,
        subtitleId: 2,
        year: 2021,
        size: '1.9 GB',
        quality: '1080p',
        youtubelink: 'https://youtube.com/example-echoes-time',
        status: 'Available',
        genreId: 8,
        downloadlinkId: 2,
        categoryId: 2
    },
    {
        id: 17,
        title: 'The Infinite War',
        slug: 'the-infinite-war',
        languageId: 1,
        bgposter: 'https://image.tmdb.org/t/p/w500/we3d798pPaPWAYOYgfVULj0I61R.jpg',
        description: 'In a future where war never ends, a group of soldiers discovers the true cause behind the conflict.',
        rating: 8.4,
        duration: 155,
        subtitleId: 2,
        year: 2024,
        size: '2.5 GB',
        quality: '4K',
        youtubelink: 'https://youtube.com/example-infinite-war',
        status: 'Available',
        genreId: 13,
        downloadlinkId: 2,
        categoryId: 2
    }
]


